### ISSUE TITLE
内存溢出？

### ISSUE THREAD

**Issue by ArielHeleneto** [Mmx233/BitSrunLoginGo#41]
下载 1.6.2 版本的 bitsrun_linux_arm64.tar.gz   或者用 https://github.com/immortalwrt/packages/blob/master/net/bitsrunlogin-go/Makefile 改成1.6.2版本都有此问题。

运行于 openwrt on MT6000

```
root@Ariel-AP:~# ./bitsrun 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x71 pc=0x3597cc]

goroutine 1 [running]:
github.com/Mmx233/BitSrunLoginGo/internal/config.initLogPre()
        github.com/Mmx233/BitSrunLoginGo/internal/config/log.go:21 +0xec
github.com/Mmx233/BitSrunLoginGo/internal/config.init.0()
        github.com/Mmx233/BitSrunLoginGo/internal/config/config.go:27 +0x20
``` 

应该如何开始排障。

**Comment by ArielHeleneto** [comment]
1.6.1是好的

**Comment by Mmx233** [comment]
Fixed in [v1.6.3](https://github.com/Mmx233/BitSrunLoginGo/releases/tag/v1.6.3)
